export const navLinks = [
  {
    id: "home",
    name: "Home",
    linkId: "/#home",
  },
  {
    id: "about",
    name: "About",
    linkId: "/#about",
  },
  {
    id: "projects",
    name: "Projects",
    linkId: "/#projects",
  },
  {
    id: "skills",
    name: "Skills",
    linkId: "/#skills",
  },
  {
    id: "contact",
    name: "Contact",
    linkId: "/#contact",
  },
];

export const projects = [
  {
    id: "swiftmessenger",
    name: "Swift Messenger",
    description:
      "Built a messaging app using the MERN stack, offering one-on-one and group chats with real-time communication through Socket.io. We prioritize security with user authorization using JWT and secure user data storage using bcrypt encryption. The app also includes admin-controlled user management for group chats, allowing administrators to add and remove users with ease.",
    skills: [
      "ReactJS",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Socket.io",
      "Web Token",
      "Git",
    ],
    image: "/assets/swift.png",
    coverImage: "/assets/swiftMessenger.png",
    Link: "/project/swiftmessenger",
    RepoLink: "https://github.com/SahilLamba0008/Swift-Messenger",
    LiveLink: "",
    VideoLink: "https://youtube.com/embed/Xc9gvr9XpmQ?rel=0",
    keyPoints: [
      "Developed a messaging app supporting one-on-one and group conversations using the MERN stack.",
      "Integrated real-time communication features powered by Socket.io.",
      "Implemented secure user authorization using JWT.",
      "Ensured password encryption with bcrypt for secure storage of user information.",
      "Developed admin-controlled user management features.",
      "Enabled administrators to add and remove users from group chats.",
    ],
    skillsSvg: ["/assets/svgs/socket-io.svg", "/assets/svgs/react.svg", "/assets/svgs/javascript.svg","/assets/svgs/nodejs.svg", "/assets/svgs/express.svg", "/assets/svgs/jwt.svg", "/assets/svgs/mongodb.svg", "/assets/svgs/postman.svg", "/assets/svgs/axios.svg",  "/assets/svgs/chakra-ui.png", "/assets/svgs/git.svg"],
    even: false,
  },
  {
    id: "digitalmart",
    name: "Digital Mart",
    description:
      "Designed an electronics-centered e-commerce website using ReactJs and Styled Components, ensuring a user-friendly and responsive interface for shopping digital products. The platform offers advanced features such as state management, product filtering, dynamic price sorting, and responsive UI. It also includes client-side form validation for a secure and smooth user experience and integrates Axios for seamless API data retrieval.",
    skills: [
      "ReactJS",
      "JavaScript",
      "Context API",
      "Axios",
      "Styled - Components(CSS)",
      "Git",
    ],
    image: "/assets/mart.png",
    coverImage: "/assets/digitMart.png",
    Link: "/project/digitalmart",
    RepoLink: "https://github.com/SahilLamba0008/Digital-Mart",
    LiveLink: "https://tranquil-raindrop-bfb648.netlify.app/",
    VideoLink: "https://youtube.com/embed/Xc9gvr9XpmQ?rel=0",
    keyPoints: [
      "Leveraged <span>useState</span> , <span>useReducer</span> and <span>Context API</span> for efficient state management and React Router DOM for seamless navigation.",
      "Implemented dynamic features like product rating, product filtering and responsive design.",
      "Intergrated from validation and fetched API data using react-axios library.",
    ],
    skillsSvg: ["/assets/svgs/react.svg", "/assets/svgs/javascript.svg","/assets/svgs/styled-components.svg", "/assets/svgs/axios.svg", "/assets/svgs/git.svg"],
    even: true,
  },
  {
    id: "dinehub",
    name: "Dine Hub",
    description:
      "Developed an engaging front-end food ordering application using React, JavaScript, and CSS. The app features dynamic components, including carousels, to enhance user engagement. For smooth navigation, React Router DOM was used to transition between various pages. Advanced filtering options and interactive user design were implemented for an enjoyable experience. CSS Grids, Flexbox, and StyledComponents were employed to craft an interactive platform for restaurant exploration and food ordering.",
    skills: [
      "ReactJS",
      "JSX",
      "JavaScript",
      "React Router",
      "CSS",
      "Carousels",
      "Conditional Classes",
      "Git",
    ],
    image: "/assets/dine.png",
    coverImage: "/assets/dinehub.png",
    Link: "/project/dinehub",
    RepoLink: "https://github.com/SahilLamba0008/Dine-Hub",
    LiveLink: "",
    VideoLink: "https://youtube.com/embed/Xc9gvr9XpmQ?rel=0",
    keyPoints: [
      "Developed an interactive food ordering app featuring dynamic components like carousels for enhanced user engagement using React , JavaScript , and CSS.",
      "Integrated advanced filtering features, interactive user design and state management using React Hooks and JavaScript Event-Handling.",
      "Styled using CSS Grids , Flexbox , and StyledComponents , creating an interactive place for exploring restaurants and ordering food.",
    ],
    skillsSvg: ["/assets/svgs/react.svg", "/assets/svgs/javascript.svg","/assets/svgs/css-3.svg","/assets/svgs/react-router.png", "/assets/svgs/git.svg"],
    even: false,
  },
];

export const skills = [
  {
    id: "javascript",
    name: "JavaScript",
    link: "",
    image: "/assets/skills/javascript.png",
  },
  {
    id: "typescript",
    name: "TypeScript",
    link: "",
    image: "/assets/skills/typescript.png",
  },
  {
    id: "cpp",
    name: "C++",
    link: "",
    image: "/assets/skills/cpp.png",
  },
  {
    id: "react",
    name: "React",
    link: "",
    image: "/assets/skills/react.png",
  },
  {
    id: "nextjs",
    name: "Nextjs",
    link: "",
    image: "/assets/skills/nextjs.png",
  },
  {
    id: "nodejs",
    name: "NodeJS",
    link: "",
    image: "/assets/skills/nodejs.png",
  },
  {
    id: "expressjs",
    name: "ExpressJS",
    link: "",
    image: "/assets/skills/expressjs.png",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    link: "",
    image: "/assets/skills/mongo-db.png",
  },
  {
    id: "mysql",
    name: "MySql",
    link: "",
    image: "/assets/skills/mysql.png",
  },
  {
    id: "html",
    name: "HTML",
    link: "",
    image: "/assets/skills/html.png",
  },
  {
    id: "css",
    name: "CSS",
    link: "",
    image: "/assets/skills/css.png",
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    link: "",
    image: "/assets/skills/bootstrap.png",
  },
  {
    id: "tailwind",
    name: "Tailwind",
    link: "",
    image: "/assets/skills/tailwind.png",
  },
  {
    id: "figma",
    name: "Figma",
    link: "",
    image: "/assets/skills/figma.png",
  },
  {
    id: "vscode",
    name: "VsCode",
    link: "",
    image: "/assets/skills/vs-code.png",
  },
];
